### ISSUE TITLE
IRSE S7 stock enabling works

### ISSUE THREAD

**Issue by tjvr** [artemis-beta/EdgwareRoadSignalBox#2]
This looks relevant to you, if you haven't seen it:
https://www.irse.org/LinkClick.aspx?fileticket=Ut-meuzKGAE%3D&portalid=0

**Comment by zarethrex** [comment]
@tjvr this refers to post-modernisation though right? The simulation is focusing on the manual operation as opposed to automatic.

**Comment by tjvr** [comment]
Oh maybe, sorry! I thought there was mention of interfacing with the old box :-)
